//! Bulk rewrite from a `BindCollection`.
//!
//! Used by the bundle importer: takes a fully-populated `BindCollection`
//! and rewrites every managed section in one pass. Unmanaged Lua outside
//! markers is preserved.

use std::collections::BTreeMap;
use std::path::Path;

use crate::bind::{BindCollection, Keybind};
use crate::keys::lua_string_literal;
use crate::settings_config;
use crate::spec;
use crate::window_rules;
use crate::writer::error::{ok_result, write_config_atomic, WriteError, WriteMode, WriteResult};
use crate::writer::lua_text::{format_action, format_keys, format_opts, is_lua_ident};
use crate::writer::section::{
    join_section_entries, replace_managed_section_contents, MANAGED_ANIMS_BEGIN, MANAGED_ANIMS_END,
    MANAGED_BINDS_BEGIN, MANAGED_BINDS_END, MANAGED_CONFIG_BEGIN, MANAGED_CONFIG_END,
    MANAGED_CURVES_BEGIN, MANAGED_CURVES_END, MANAGED_DEVICES_BEGIN, MANAGED_DEVICES_END,
    MANAGED_ENV_BEGIN, MANAGED_ENV_END, MANAGED_GESTURES_BEGIN, MANAGED_GESTURES_END,
    MANAGED_LAYER_RULES_BEGIN, MANAGED_LAYER_RULES_END, MANAGED_MONITORS_BEGIN,
    MANAGED_MONITORS_END, MANAGED_RULES_BEGIN, MANAGED_RULES_END, MANAGED_STARTUP_BEGIN,
    MANAGED_STARTUP_END, MANAGED_SUBMAPS_BEGIN, MANAGED_SUBMAPS_END, MANAGED_VARS_BEGIN,
    MANAGED_VARS_END, MANAGED_WS_RULES_BEGIN, MANAGED_WS_RULES_END,
};
use crate::writer::startup::{format_exec_cmd_line, normalize_when};

/// Rewrite every hyprbinds managed section from a collected model.
///
/// Unmanaged Lua outside markers is preserved. Entries that cannot be
/// translated (e.g. Lua-function bind actions) are skipped.
pub fn apply_collection(
    config_path: &Path,
    collection: &BindCollection,
) -> Result<WriteResult, WriteError> {
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    if !config_path.is_file() {
        std::fs::write(
            config_path,
            "-- Generated by hyprbinds import\nlocal hl = require(\"hyprland\")\n",
        )?;
    }

    let mut source = std::fs::read_to_string(config_path)?;

    // --- Variables ---
    {
        let mut lines = Vec::new();
        for var in &collection.variables {
            let name = var.name.trim();
            if name.is_empty() || !is_lua_ident(name) {
                continue;
            }
            lines.push(format!(
                "local {name} = {}",
                lua_string_literal(&var.value)
            ));
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_VARS_BEGIN,
            MANAGED_VARS_END,
            &join_section_entries(&lines),
        )?;
    }

    // --- Root binds (empty submap) ---
    {
        let mut lines = Vec::new();
        for bind in collection.binds.iter().filter(|b| b.submap.trim().is_empty()) {
            if let Some(line) = format_bind_line(bind) {
                lines.push(line);
            }
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_BINDS_BEGIN,
            MANAGED_BINDS_END,
            &join_section_entries(&lines),
        )?;
    }

    // --- Submaps (+ their binds) ---
    {
        let mut by_submap: BTreeMap<String, Vec<&Keybind>> = BTreeMap::new();
        for bind in &collection.binds {
            let sm = bind.submap.trim();
            if sm.is_empty() {
                continue;
            }
            by_submap.entry(sm.to_string()).or_default().push(bind);
        }
        for sub in &collection.submaps {
            let name = sub.name.trim();
            if name.is_empty() {
                continue;
            }
            by_submap.entry(name.to_string()).or_default();
        }
        let mut blocks = Vec::new();
        for (name, binds) in &by_submap {
            let mut body = Vec::new();
            for bind in binds {
                if let Some(line) = format_bind_line(bind) {
                    body.push(format!("  {line}"));
                }
            }
            if body.is_empty() {
                body.push(format!("  -- binds for {name}"));
            }
            blocks.push(format!(
                "hl.define_submap({}, function()\n{}\nend)",
                lua_string_literal(name),
                body.join("\n")
            ));
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_SUBMAPS_BEGIN,
            MANAGED_SUBMAPS_END,
            &join_section_entries(&blocks),
        )?;
    }

    // --- Env ---
    {
        let mut lines = Vec::new();
        for env in &collection.env {
            let name = env.name.trim();
            if name.is_empty() {
                continue;
            }
            lines.push(format!(
                "hl.env({}, {})",
                lua_string_literal(name),
                lua_string_literal(&env.value)
            ));
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_ENV_BEGIN,
            MANAGED_ENV_END,
            &join_section_entries(&lines),
        )?;
    }

    // --- Startup ---
    {
        let mut reload = Vec::new();
        let mut start = Vec::new();
        let mut shutdown = Vec::new();
        for entry in &collection.startup {
            let cmd = entry.command.trim();
            if cmd.is_empty() {
                continue;
            }
            let when = normalize_when(&entry.when).unwrap_or("start");
            match when {
                "reload" => reload.push(format_exec_cmd_line(cmd, &entry.workspace, "")),
                "shutdown" => shutdown.push(format_exec_cmd_line(cmd, &entry.workspace, "  ")),
                _ => start.push(format_exec_cmd_line(cmd, &entry.workspace, "  ")),
            }
        }
        let mut body = String::new();
        if !reload.is_empty() {
            body.push_str(&reload.join("\n"));
            body.push('\n');
        }
        body.push_str("hl.on(\"hyprland.start\", function()\n");
        if start.is_empty() {
            body.push_str("end)\n");
        } else {
            body.push_str(&start.join("\n"));
            body.push_str("\nend)\n");
        }
        body.push_str("hl.on(\"hyprland.shutdown\", function()\n");
        if shutdown.is_empty() {
            body.push_str("end)");
        } else {
            body.push_str(&shutdown.join("\n"));
            body.push_str("\nend)");
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_STARTUP_BEGIN,
            MANAGED_STARTUP_END,
            &body,
        )?;
    }

    // --- Window rules ---
    {
        let mut blocks = Vec::new();
        for rule in &collection.window_rules {
            if rule.match_props.is_empty() && rule.effects.is_empty() {
                continue;
            }
            blocks.push(window_rules::format_lua_rule(
                &rule.name,
                &rule.match_props,
                &rule.effects,
            ));
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_RULES_BEGIN,
            MANAGED_RULES_END,
            &join_section_entries(&blocks),
        )?;
    }

    // --- Layer rules ---
    {
        let mut blocks = Vec::new();
        for rule in &collection.layer_rules {
            if rule.match_props.is_empty() && rule.effects.is_empty() {
                continue;
            }
            let block = window_rules::format_lua_rule(
                &rule.name,
                &rule.match_props,
                &rule.effects,
            )
            .replacen("hl.window_rule", "hl.layer_rule", 1);
            blocks.push(block);
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_LAYER_RULES_BEGIN,
            MANAGED_LAYER_RULES_END,
            &join_section_entries(&blocks),
        )?;
    }

    // --- Spec sections ---
    let spec_sections = [
        (
            MANAGED_WS_RULES_BEGIN,
            MANAGED_WS_RULES_END,
            "hl.workspace_rule",
            &collection.workspace_rules,
            true,
        ),
        (
            MANAGED_MONITORS_BEGIN,
            MANAGED_MONITORS_END,
            "hl.monitor",
            &collection.monitors,
            true,
        ),
        (
            MANAGED_DEVICES_BEGIN,
            MANAGED_DEVICES_END,
            "hl.device",
            &collection.devices,
            true,
        ),
        (
            MANAGED_GESTURES_BEGIN,
            MANAGED_GESTURES_END,
            "hl.gesture",
            &collection.gestures,
            false,
        ),
        (
            MANAGED_ANIMS_BEGIN,
            MANAGED_ANIMS_END,
            "hl.animation",
            &collection.animations,
            false,
        ),
    ];
    for (begin, end, fn_name, items, use_name) in spec_sections {
        let mut blocks = Vec::new();
        for item in items {
            if item.fields.is_empty() {
                continue;
            }
            let name = if use_name {
                let n = item.name.trim();
                if n.is_empty() {
                    None
                } else {
                    Some(n)
                }
            } else {
                None
            };
            blocks.push(spec::format_call(fn_name, &item.fields, name));
        }
        source = replace_managed_section_contents(
            &source,
            begin,
            end,
            &join_section_entries(&blocks),
        )?;
    }

    // --- Curves ---
    {
        let mut blocks = Vec::new();
        for item in &collection.curves {
            let name = if item.name.trim().is_empty() {
                item.display_name.trim()
            } else {
                item.name.trim()
            };
            if name.is_empty() {
                continue;
            }
            blocks.push(spec::format_curve_call(name, &item.fields));
        }
        source = replace_managed_section_contents(
            &source,
            MANAGED_CURVES_BEGIN,
            MANAGED_CURVES_END,
            &join_section_entries(&blocks),
        )?;
    }

    // --- Config overrides ---
    {
        let filtered = settings_config::filter_mvp(&collection.config_merged);
        let call = spec::format_config_call(&filtered);
        source = replace_managed_section_contents(
            &source,
            MANAGED_CONFIG_BEGIN,
            MANAGED_CONFIG_END,
            &call,
        )?;
    }

    write_config_atomic(config_path, &source)?;
    Ok(ok_result(
        config_path.display().to_string(),
        WriteMode::Materialized,
    ))
}

fn format_bind_line(bind: &crate::bind::Keybind) -> Option<String> {
    let keys = bind.keys.trim();
    let action = bind.action.trim();
    let name = if bind.name.trim().is_empty() {
        bind.description.trim()
    } else {
        bind.name.trim()
    };
    if keys.is_empty() || action.is_empty() {
        return None;
    }
    if action.starts_with('<') {
        return None;
    }
    let keys_expr = format_keys(keys).ok()?;
    let action_expr = format_action(action, "").ok()?;
    let opts = format_opts(&bind.flags, if name.is_empty() { "untitled" } else { name });
    Some(format!("hl.bind({keys_expr}, {action_expr}, {opts})"))
}
